/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing.heranca;

/**
 *
 * @author NOLE201903
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMaratonista = new javax.swing.JButton();
        btVelocista = new javax.swing.JButton();
        brTriatleta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbFisico = new javax.swing.JLabel();
        lbTempo = new javax.swing.JLabel();
        lbPerformance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btMaratonista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btMaratonista.setForeground(new java.awt.Color(0, 0, 0));
        btMaratonista.setText("NASCE UM MARATONISTA");
        btMaratonista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaratonistaActionPerformed(evt);
            }
        });

        btVelocista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btVelocista.setForeground(new java.awt.Color(0, 0, 0));
        btVelocista.setText("NASCE UM VELOCISTA");
        btVelocista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVelocistaActionPerformed(evt);
            }
        });

        brTriatleta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        brTriatleta.setForeground(new java.awt.Color(0, 0, 0));
        brTriatleta.setText("NASCE UM TRIATLETA");
        brTriatleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brTriatletaActionPerformed(evt);
            }
        });

        jLabel1.setText("PERFORMANCE:");

        jLabel2.setText("TIPO FÍSICO:");

        jLabel3.setText("TEMPO MÉDIO CORRENDO:");

        lbFisico.setText("...");

        lbTempo.setText("...");

        lbPerformance.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btMaratonista)
                        .addGap(18, 18, 18)
                        .addComponent(btVelocista)
                        .addGap(18, 18, 18)
                        .addComponent(brTriatleta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(lbPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(259, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMaratonista)
                    .addComponent(btVelocista)
                    .addComponent(brTriatleta))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addComponent(lbTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(lbPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMaratonistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaratonistaActionPerformed
        Corredor maratonista = new Maratonista();
        
        lbFisico.setText(maratonista.getTipoFisico());
        lbPerformance.setText(maratonista.getPerformance());
        lbTempo.setText(maratonista.getTempoMedio().toString());
    }//GEN-LAST:event_btMaratonistaActionPerformed

    private void btVelocistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVelocistaActionPerformed
        Corredor velocista = new Velocista();
        
        lbFisico.setText(velocista.getTipoFisico());
        lbPerformance.setText(velocista.getPerformance());
        lbTempo.setText(velocista.getTempoMedio().toString());
    }//GEN-LAST:event_btVelocistaActionPerformed

    private void brTriatletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brTriatletaActionPerformed
        Corredor triatleta = new TriAtleta();
        
        lbFisico.setText(triatleta.getTipoFisico());
        lbPerformance.setText(triatleta.getPerformance());
        lbTempo.setText(triatleta.getTempoMedio().toString());
    }//GEN-LAST:event_brTriatletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brTriatleta;
    private javax.swing.JButton btMaratonista;
    private javax.swing.JButton btVelocista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbFisico;
    private javax.swing.JLabel lbPerformance;
    private javax.swing.JLabel lbTempo;
    // End of variables declaration//GEN-END:variables
}
