/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing.encapsulamento;

/**
 *
 * @author NOLE201903
 */
public class Exercicio1 extends javax.swing.JFrame {
    
    UrnaEletronica urna = new UrnaEletronica();
    
    /**
     * Creates new form Exercicio1
     */
    public Exercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGryffindor = new javax.swing.JButton();
        btSlytherin = new javax.swing.JButton();
        lbQV1 = new javax.swing.JLabel();
        lbQV2 = new javax.swing.JLabel();
        lbVotosG = new javax.swing.JLabel();
        lbVotosS = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btGryffindor.setBackground(new java.awt.Color(153, 0, 0));
        btGryffindor.setForeground(new java.awt.Color(255, 153, 0));
        btGryffindor.setText("VOTAR GRYFFINDOR");
        btGryffindor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGryffindorActionPerformed(evt);
            }
        });

        btSlytherin.setBackground(new java.awt.Color(0, 51, 0));
        btSlytherin.setForeground(new java.awt.Color(153, 153, 153));
        btSlytherin.setText("VOTAR SLYTHERIN");

        lbQV1.setText("VOTOS:");

        lbQV2.setText("VOTOS:");

        lbVotosG.setText("0");

        lbVotosS.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btGryffindor)
                            .addComponent(btSlytherin))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbQV2)
                                .addGap(18, 18, 18)
                                .addComponent(lbVotosS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbQV1)
                                .addGap(18, 18, 18)
                                .addComponent(lbVotosG)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGryffindor)
                    .addComponent(lbQV1)
                    .addComponent(lbVotosG))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSlytherin)
                    .addComponent(lbQV2)
                    .addComponent(lbVotosS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGryffindorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGryffindorActionPerformed
     
    }//GEN-LAST:event_btGryffindorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookanlbResultadoaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGryffindor;
    private javax.swing.JButton btSlytherin;
    private javax.swing.JLabel lbQV1;
    private javax.swing.JLabel lbQV2;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbVotosG;
    private javax.swing.JLabel lbVotosS;
    // End of variables declaration//GEN-END:variables
}
