/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing;

import java.awt.Color;

/**
 *
 * @author NOLE201903
 */
public class TelaComponentes extends javax.swing.JFrame {

        //novo atributo: "Clique", do tipo integer
        Integer cliques = 0;
    
    /**
     * Creates new form TelaComponentes
     */
    public TelaComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbProgresso = new javax.swing.JProgressBar();
        btAumentar = new javax.swing.JButton();
        btDiminuir = new javax.swing.JButton();
        btProgresso = new javax.swing.JButton();
        ckSolteiro = new javax.swing.JCheckBox();
        btSituacao = new javax.swing.JButton();
        lbCliques = new javax.swing.JLabel();
        btCliques = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pbProgresso.setValue(20);

        btAumentar.setText("Aumentar");
        btAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAumentarActionPerformed(evt);
            }
        });

        btDiminuir.setText("Diminuir");
        btDiminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDiminuirActionPerformed(evt);
            }
        });

        btProgresso.setText("Valor 50");
        btProgresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProgressoActionPerformed(evt);
            }
        });

        ckSolteiro.setText("Solteiro(a)");

        btSituacao.setText("Ver Situação");
        btSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSituacaoActionPerformed(evt);
            }
        });

        lbCliques.setText("Quantos cliques: 0");

        btCliques.setText("Clica Aqui!");
        btCliques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCliquesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCliques)
                        .addGap(18, 18, 18)
                        .addComponent(btCliques))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckSolteiro)
                        .addGap(27, 27, 27)
                        .addComponent(btSituacao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pbProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAumentar)
                        .addGap(18, 18, 18)
                        .addComponent(btDiminuir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btProgresso)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAumentar)
                            .addComponent(btDiminuir)
                            .addComponent(btProgresso)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pbProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckSolteiro)
                    .addComponent(btSituacao))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbCliques))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btCliques)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProgressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProgressoActionPerformed
        pbProgresso.setValue(50);
    }//GEN-LAST:event_btProgressoActionPerformed

    private void btAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAumentarActionPerformed
       pbProgresso.setValue(pbProgresso.getValue()+10);
    }//GEN-LAST:event_btAumentarActionPerformed

    private void btDiminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDiminuirActionPerformed
        pbProgresso.setValue(pbProgresso.getValue()-5);
    }//GEN-LAST:event_btDiminuirActionPerformed

    private void btSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSituacaoActionPerformed
        //Verificando se um checkbox está marcado
        if(ckSolteiro.isSelected()){
            ckSolteiro.setForeground(Color.green);
        }else{
            ckSolteiro.setForeground(Color.red);}
    }//GEN-LAST:event_btSituacaoActionPerformed

    private void btCliquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCliquesActionPerformed
        cliques++;
        lbCliques.setText("Quantos cliques: "+ cliques);
    }//GEN-LAST:event_btCliquesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAumentar;
    private javax.swing.JButton btCliques;
    private javax.swing.JButton btDiminuir;
    private javax.swing.JButton btProgresso;
    private javax.swing.JButton btSituacao;
    private javax.swing.JCheckBox ckSolteiro;
    private javax.swing.JLabel lbCliques;
    private javax.swing.JProgressBar pbProgresso;
    // End of variables declaration//GEN-END:variables
}
